### PR TITLE
Add geocodes to groups

### PR DESCRIPTION
**Pull request by viktorsheep**
Hello,
I have made the changes accordingly to the previous comments.
Here are the changes I have made : 

- Fixed unnecessary changes made on code styling.
- Added fallback address if the provided address is invalid.
- Added support for multiple addresses.
- Added support for different type of addresses ( address / coordinates ) to multiple addresses.

### CODE REVIEW

**Comment by corsacca** [comment]
Nice work @viktorsheep!
1. The geocoding process is slow, let's avoid trying to geocode empty addresses:
image

2. I'm surprised that "Church basement" was geocoded. Mapbox returns a "relevance" score. If the relevance score is <= 0.5 then we don't want to geocode the address. We should instead save it to the "contact_address" field.
I can't tell on first glance if the same is available with google geocode. 

3. As you can see the continuous integration failed. These are security and styling issues that need to be fixed. To see details you can click on the red `x` on the latest commit. 
To fix run 
`composer install`
then run the auto fixer:
`vendor/bin/phpcbf .`
then list the remaining issues by running 
`vendor/bin/phpcs`

**Comment by viktorsheep** [comment]
Hi @corsacca !
I have made the changes as per your comments, except for relevance score with Google API.
I couldn't find any response that is equals to Mapbox's relevance score in google's response.
Other than that I have made the remaining changes, here are the changes I've made : 

- Stop adding to address / geocode if the address field is blank
- Added relevance score validation ( not adding if score is below 0.5 ) when using MapBox API
- Fixed incorrect variable naming conventions by using `phpcbf`

**Comment by viktorsheep** [comment]
Hi @corsacca !
I have made the changes as per your comments, except for relevance score with Google API.
I couldn't find any response that is equals to Mapbox's relevance score in google's response.
Other than that I have made the remaining changes, here are the changes I've made : 

- Stop adding to address / geocode if the address field is blank
- Added relevance score validation ( not adding if score is below 0.5 ) when using MapBox API
- Fixed incorrect variable naming conventions by using `phpcbf`

**Comment by corsacca** [comment]
Thanks @viktorsheep ! Nice work.

**Pull request merged**
